# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 19:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_auto_20160508_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='author',
            field=models.ForeignKey(help_text="Soul sign's author", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sign',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Creation time'),
        ),
        migrations.AlterField(
            model_name='sign',
            name='expires',
            field=models.DateTimeField(blank=True, help_text='Time to live', null=True),
        ),
        migrations.AlterField(
            model_name='sign',
            name='text',
            field=models.CharField(help_text='Description of the sign', max_length=200),
        ),
    ]
