# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 10:33
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0003_auto_20160530_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='location',
            field=geoposition.fields.GeopositionField(default=40, max_length=42),
            preserve_default=False,
        ),
    ]
